### ISSUE TITLE
Improve npm override support

### ISSUE THREAD

**Issue by jdalton** [SocketDev/socket-cli-js#222]
See https://github.com/npm/cli/pull/7025#issuecomment-2407453772

Because `@socketsecurity/cli` wraps `npm` we have the opportunity to patch its overrides behavior.
@AlonNavon thoughtfully put their learnings so far in https://github.com/npm/cli/pull/7025.

**Comment by jdalton** [comment]
@AlonNavon I've backed channeled a bit with `npm`. Let's see in the next week or so. There may be more engagement on your PR to push it through.

**Comment by bcomnes** [comment]
Any clue what the holdup is?

**Comment by jdalton** [comment]
A npm maintainer replied ✨ https://github.com/npm/cli/pull/7025#issuecomment-2407888505 :heart:
I'll help review over there and implement a quick and dirty solution here.

**Comment by jdalton** [comment]
Fixed via https://github.com/SocketDev/socket-cli-js/commit/644ed42c0b78d6abe8fdce4a0deb03f03b58eb95 and https://github.com/SocketDev/socket-cli-js/commit/28e5b3d2fe740030ccb447484223d10c325c0aeb
