### ISSUE TITLE
524 error when creating a report

### ISSUE THREAD

**Issue by Mittelblut9** [SocketDev/socket-cli-js#34]
Hey 👋 
i get a 524 error when trying to create a report. I have 35 Dependecies in my package.json list currently.

![grafik](https://user-images.githubusercontent.com/67608550/227341766-c774670e-930d-4732-896e-2ab8bb63f8e4.png)

Host: Docker (Node18.8 Image)
Node: 18.8

**Comment by bmeck** [comment]
This seems odd but means there was a timeout somewhere. I'm wondering how large the total transitive installation is as this likely just means that installing the complete dependency took too long for some reason.

**Comment by Mittelblut9** [comment]
@bmeck node_modules is about 212MB
