### ISSUE TITLE
socketsecurity/cli failed, reason: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by AddictArts** [SocketDev/socket-cli-js#43]
Well it would be nice to try this but I can't. Bummer, because I heard the changelog++ JS Party podcast and all the hype to result in an epic fail.

Ubuntu 22.04 LTS

**Comment by bmeck** [comment]
What does `host socket.dev` `host api.socket.dev` and `host registry.npmjs.org` give you? That seems like an error where your DNS isn't resolving a host's IP.

**Comment by AddictArts** [comment]
I give up, I guess there is no Windows option WSL or other.
