### ISSUE TITLE
Volta compatibility

### ISSUE THREAD

**Issue by novemberborn** [SocketDev/socket-cli-js#87]
I use https://volta.sh/ to manage my `node` and `npm` versions. So far I've identified two incompatibility issues.

On my machine, multiple npm versions are installed under `/opt/homebrew/var/volta/tools/image/npm/9.4.0` where `9.4.0` is a version number. So different versions have different directories.

`findRoot()` looks for an `npm` directory, which is the _parent_ directory to the npm version that is currently active:

 https://github.com/SocketDev/socket-cli-js/blob/137f0b635f858123304d006ad76ad019f7825996/lib/shadow/npm-injection.cjs#L260 

Volta inserts a binstub, so the `npm` command is actually a shell script that invokes a separate `npm-cli.js`. Socket tries to spawn that shell script and fails:

https://github.com/SocketDev/socket-cli-js/blob/137f0b635f858123304d006ad76ad019f7825996/lib/shadow/npm-cli.cjs#L14

**Comment by jdalton** [comment]
@novemberborn  Do you know what the binstub/binlauncher looks like?

**Comment by jdalton** [comment]
@novemberborn Related to #233. Did the `package-lock.json` get updated for you using `socket optimize`. Is Volta compatibility still an issue? I'm wanting to fix compat (be maximally compatible) but need more Volta info 💡

**Comment by novemberborn** [comment]
> Related to #233. Did the `package-lock.json` get updated for you using `socket optimize`.

I believe so, yes.



> Is Volta compatibility still an issue? I'm wanting to fix compat (be maximally compatible) but need more Volta info 💡

I'm trying to recall what feature I was trying to use here. Presumably the wrapper. I just tried that and it seemed to work, however I did recently clean up my Volta installation so perhaps the original issue relates to a setup I can no longer reproduce.

**Comment by jdalton** [comment]
Okay! I'll close this for now. Will open again if the issue pops up.
